spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.65.129:3306/db_hbfqlx_spot?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Ming.&125226

    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: hikariDataSource
      connection-timeout: 30000
      connection-test-query: SELECT 1
      type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  mapperLocations: classpath*:mapper/*.xml

